Repository Speedfan94/PDS_Project, pull requests merged in 2020-06, with the labels that each got.

#79 Feat/docstrings
  nextbike/cli.py
  nextbike/datapreparation/data_clean.py
  nextbike/datapreparation/feature_add.py
  nextbike/io/input.py
  nextbike/io/output.py
  nextbike/io/utils.py
  nextbike/prediction/geo_predict.py
  nextbike/prediction/math_predict.py
  nextbike/prediction/math_prepare_feature.py
  nextbike/prediction/math_split.py
  nextbike/prediction/math_train.py
  nextbike/visualization/math.py
Labels: module/cleaning, module/modeling_prediction, module/visualization_plotting, type/documentation

#84 Feat/docstrings
  nextbike/io/utils.py
  nextbike/utils.py
Labels: Finalization, type/documentation

#85 Feat/plz tuning max
  nextbike/cli.py
  nextbike/data/output/data_plots/geo/Moment.html
  nextbike/data/output/data_plots/geo/Month_Nuremberg.html
  nextbike/data/output/data_plots/geo/One-Day-in-Nuremberg.html
  nextbike/data/output/data_plots/math/Correlation.png
  nextbike/data/output/data_plots/math/DurationMinutes_Distribution.png
  nextbike/data/output/data_plots/math/Mean_Duration_per_Day.png
  nextbike/data/output/data_plots/math/aggr_stats_whole_df.png
  nextbike/data/output/models/Linear_Regression_Model.pkl
  nextbike/data/output/models/Neural_Network_Model/saved_model.pb
  nextbike/data/output/models/Neural_Network_Model/variables/variables.data-00000-of-00001
  nextbike/data/output/models/Neural_Network_Model/variables/variables.index
  nextbike/data/output/models/PCA.pkl
  nextbike/data/output/models/SVM_Regression_Model_3.pkl
  nextbike/data/output/models/Standard_Scaler.pkl
  nextbike/datapreparation/geo_clean.py
  nextbike/visualization/geo.py
  notebooks/task1c_feature_creation.ipynb
  setup.py
Labels: module/cleaning, type/feature

#87 Feat/report tests
  nextbike/cli.py
  nextbike/data/output/data_plots/math/counts_day_start.png
  nextbike/data/output/data_plots/math/counts_hour_start.png
  nextbike/data/output/data_plots/math/counts_month_start.png
  nextbike/data/output/data_plots/math/means_day_start.png
  nextbike/data/output/data_plots/math/means_hour_start.png
  nextbike/data/output/data_plots/math/means_month_start.png
  nextbike/data/output/data_plots/math/stds_day_start.png
  nextbike/data/output/data_plots/math/stds_hour_start.png
  nextbike/data/output/data_plots/math/stds_month_start.png
  nextbike/prediction/geo_predict.py
  nextbike/prediction/math_prepare_feature.py
  nextbike/prediction/math_train.py
  nextbike/testing/__init__.py
  nextbike/testing/model_testing.py
  nextbike/visualization/math_predictive.py
  notebooks/Direction exploration.ipynb
Labels: module/modeling_prediction, module/visualization_plotting, type/testing

#88 Feat/plz tuning max
  nextbike/datapreparation/geo_clean.py
Labels: Finalization, type/bug

#89 Reset index before saving csv files to have clean files
  nextbike/io/output.py
Labels: Finalization, type/bug

#90 Feat/omit warnings
  nextbike/cli.py
  nextbike/datapreparation/data_clean.py
  nextbike/datapreparation/feature_add.py
  nextbike/datapreparation/geo_clean.py
  nextbike/io/input.py
  nextbike/io/output.py
  nextbike/prediction/math_prepare_feature.py
  nextbike/visualization/geo.py
  nextbike/visualization/math_descriptive.py
  nextbike/visualization/math_predictive.py
Labels: Finalization, module/cleaning, type/bug

#102 Feat/close plots
  nextbike/visualization/math_descriptive.py
Labels: Finalization, module/visualization_plotting, type/bug

#103 chore(documentation): add pictures for report
  documentation/moment.png
  documentation/report-frontpage_1.png
  documentation/report-frontpage_2.png
Labels: Finalization

#112 Feat/aggr stats matplot
  nextbike/datapreparation/feature_add.py
  nextbike/prediction/prepare_feature.py
  nextbike/visualization/math_descriptive.py
Labels: Finalization, module/visualization_plotting, type/feature

#120 Feat/fix-imports
  nextbike/prediction/evaluate.py
  nextbike/prediction/geo_predict.py
  nextbike/prediction/geo_train.py
  nextbike/prediction/math_predict.py
  nextbike/prediction/math_train.py
  nextbike/prediction/prepare_feature.py
  nextbike/testing/direction_classification_subsets_testing.py
  nextbike/testing/nn_testing.py
  nextbike/testing/robust_scaler_testing.py
  nextbike/visualization/geo.py
  nextbike/visualization/math_descriptive.py
  nextbike/visualization/math_predictive.py
Labels: Finalization, optional / low prio

#121 Help Strings (cli py)
  nextbike/cli.py
  nextbike/cli_code.py
  nextbike/datapreparation/feature_add.py
  nextbike/io/output.py
  nextbike/io/utils.py
  nextbike/prediction/evaluate.py
  nextbike/prediction/geo_train.py
  nextbike/prediction/math_predict.py
  nextbike/prediction/math_train.py
  nextbike/testing/direction_classification_subsets_testing.py
  nextbike/testing/linear_regression_testing.py
  nextbike/testing/nn_testing.py
  nextbike/testing/robust_scaler_testing.py
  nextbike/visualization/geo.py
  nextbike/visualization/math_descriptive.py
  nextbike/visualization/math_predictive.py
Labels: Finalization, type/documentation

#124 feat (nextbike/..): selectable weather and mode in cli.py
  nextbike/cli.py
  nextbike/cli_code.py
  nextbike/data/output/NN_Metrics.csv
  nextbike/prediction/geo_predict.py
  nextbike/prediction/geo_train.py
  nextbike/prediction/math_predict.py
  nextbike/prediction/math_train.py
  nextbike/prediction/prepare_feature.py
  nextbike/prediction/split.py
  nextbike/testing/direction_classification_subsets_testing.py
  nextbike/testing/nn_testing.py
  nextbike/testing/robust_scaler_testing.py
  nextbike/visualization/geo.py
  nextbike/visualization/math_descriptive.py
  nextbike/visualization/math_predictive.py
Labels: Finalization, type/bug, type/documentation, type/feature, type/testing

#125 Feat/plot fontsize
  nextbike/visualization/math_descriptive.py
  nextbike/visualization/math_predictive.py
Labels: Finalization, module/visualization_plotting, type/feature

#127 Feat/docstrings
  nextbike/cli.py
  nextbike/cli_code.py
  nextbike/prediction/evaluate.py
  nextbike/prediction/geo_predict.py
  nextbike/prediction/geo_train.py
  nextbike/prediction/math_predict.py
  nextbike/prediction/math_train.py
  nextbike/prediction/prepare_feature.py
  nextbike/testing/direction_classification_subsets_testing.py
  nextbike/testing/linear_regression_testing.py
  nextbike/testing/nn_testing.py
  nextbike/testing/robust_scaler_testing.py
  nextbike/visualization/math_descriptive.py
Labels: Finalization, type/documentation

#129 Feat/subet line plots
  nextbike/cli_code.py
  nextbike/visualization/math_descriptive.py
Labels: Finalization, module/visualization_plotting, type/feature

#130 Release version of dev into master
  README.md
  nextbike/cli.py
  nextbike/cli_code.py
  nextbike/data/output/NN_Metrics.csv
  nextbike/datapreparation/feature_add.py
  nextbike/prediction/evaluate.py
  nextbike/prediction/geo_predict.py
  nextbike/prediction/geo_train.py
  nextbike/prediction/math_predict.py
  nextbike/prediction/math_train.py
  nextbike/prediction/prepare_feature.py
  nextbike/prediction/split.py
  nextbike/testing/direction_classification_subsets_testing.py
  nextbike/testing/linear_regression_testing.py
  nextbike/testing/nn_testing.py
  nextbike/testing/robust_scaler_testing.py
  nextbike/visualization/geo.py
  nextbike/visualization/math_descriptive.py
  nextbike/visualization/math_predictive.py
  notebooks/01_ShowData.ipynb
Labels: #projecttask, Finalization

#132 Newest updates to dev
  notebooks/01_ShowData.ipynb
Labels: Finalization, type/documentation
