Repository Speedfan94/PDS_Project, pull requests merged in 2020-05, with the labels that each got.

#47 Style/docu/features
  nextbike/__init__.py
  nextbike/cli.py
  nextbike/data/output/Month_Nuremberg.html
  nextbike/data/output/One-Day-in-Nuremberg.html
  nextbike/datapreparation/__init__.py
  nextbike/datapreparation/datapreparation.py
  nextbike/datapreparation/plz.py
  nextbike/model/__init__.py
  nextbike/model/model.py
  nextbike/plz/__init__.py
  nextbike/prediction/__init__.py
  nextbike/prediction/predict.py
  nextbike/prediction/prepare_feature.py
  nextbike/prediction/split.py
  nextbike/prediction/training.py
  nextbike/visualization/visualization.py
Labels: type/bug, type/documentation, type/feature

#50 Style/docu/features
  .gitignore
  nextbike/cli.py
  nextbike/data/output/2019-08-27 01-53-00.png
  nextbike/data/output/2019-09-01 20-59-00.png
  nextbike/data/output/2019-09-04 23-47-00.png
  nextbike/data/output/2019-12-25 17-56-00.png
  nextbike/data/output/2019-12-26 21-45-00.png
  nextbike/data/output/data_plots/2019-09-01 20-59-00.png
  nextbike/data/output/data_plots/Correlation.png
  nextbike/data/output/data_plots/One-Day-in-Nuremberg.html
  nextbike/data/output/models/Linear_Regression_Model.pkl
  nextbike/data/output/models/PCA.pkl
  nextbike/data/output/models/SVM_Regression_Model.pkl
  nextbike/data/output/models/SVM_Regression_Model_0.pkl
  nextbike/data/output/models/SVM_Regression_Model_1.pkl
  nextbike/data/output/models/SVM_Regression_Model_2.pkl
  nextbike/data/output/models/SVM_Regression_Model_3.pkl
  nextbike/data/output/models/Standard_Scaler.pkl
  nextbike/datapreparation/datapreparation.py
  nextbike/datapreparation/plz.py
  nextbike/io/input.py
  nextbike/io/output.py
  nextbike/io/utils.py
  nextbike/prediction/__init__.py
  nextbike/prediction/predict.py
  nextbike/prediction/prepare_feature.py
  nextbike/prediction/split.py
  nextbike/prediction/training.py
  nextbike/visualization/visualization.py
  notebooks/Quick_Prototyping_Kevin.ipynb
Labels: module/cleaning, module/modeling, type/feature

#56 chore(notebooks): prototype nn
  notebooks/Prototype_NN.ipynb
Labels: module/modeling, type/feature

#52 Docu/add method docu
  nextbike/cli.py
  nextbike/datapreparation/datapreparation.py
  nextbike/visualization/visualization.py
Labels: type/documentation

#62 Feat/neural network
  nextbike/cli.py
  nextbike/prediction/math_prepare_feature.py
  nextbike/visualization/math.py
Labels: type/testing

#65 Feat/check beginning ending trips
  nextbike/datapreparation/data_clean.py
  notebooks/Cleaning_Max.ipynb
Labels: module/cleaning, type/feature

#66 Feat/index column
  nextbike/cli.py
  nextbike/datapreparation/data_clean.py
  nextbike/io/input.py
  nextbike/io/output.py
Labels: module/cleaning, type/bug
